### PR TITLE
Fix pathToRDebugIDE option being ignored

### PR DESCRIPTION
**Pull request by peret**
The value of the debugger option "pathToRDebugIDE" was never used in the code. It appears that this issue was introduced with commit 12e95f41aaa53aa2f27f291760f32996a6afedc3, which apparently renamed the field without renaming the option.

This PR should fix that.

- [X] The build passes
- [X] TSLint is mostly happy
- [X] Prettier has been run

### CODE REVIEW

**Comment by yock** [comment]
@peret Is there anything I can do to help this across the finish line?

**Comment by edgetools** [comment]
any movement on this? I've got a workflow which is blocked and would love this fix :)

**Comment by peret** [comment]
I'm not sure myself, why this hasn't been merged yet. I just rebased the branch onto the latest master and actually removed the automatic code style changes to make the PR easier to review 👍

**Comment by wingrunr21** [comment]
It hasn’t been merged because I haven’t had time. I’ll mark this as not stale and review and merge it soon

**Comment by peret** [comment]
Awesome, thanks :)

**Comment by doubledgedboard** [comment]
@wingrunr21 

> I’ll mark this as not stale and review and merge it soon

SoonTM ?

**Comment by martinjozef** [comment]
Hi there, also a fan of this fix!
Just wanted add my support for this PR!
Regards.

**Pull request closed without merging**
