### PR TITLE
HAML breakpoints

### PR DESCRIPTION
**Pull request by hazg**
Add breakpoints support for HAML

Make sure these boxes are checked before submitting your PR -- thanks in advance!

- [x] Build pass!
- [x] Follow VS Code [Coding Guidelines](https://github.com/Microsoft/vscode/wiki/Coding-Guidelines)

### CODE REVIEW

**Comment by wingrunr21** [comment]
Hi @hazg,

Would you be willing to reopen this PR against my fork?

Fork: https://github.com/wingrunr21/vscode-ruby-lang

See https://github.com/rubyide/vscode-ruby/issues/239#issuecomment-359279950 for more information

Thanks!

**Comment by hrishikesh** [comment]
Can someone please merge this pr

**Comment by wingrunr21** [comment]
@hazg @hrishikesh 

It needs to be updated against current `master` before it is mergable

**Comment by baelter** [comment]
This would be awesome!

**Comment by baelter** [comment]
Still relevant

**Comment by minkir014** [comment]
Still relevant

**Comment by baelter** [comment]
Still relevant

**Pull request closed without merging**
