### PR TITLE
Every code structure which closes with end keyword is now distinguishable

### PR DESCRIPTION
**Pull request by graceful-potato**
Added ability to distinguish end keyword between `class`, `module`, `def`, `do`, `if`, `unless`, `while`, `until`, `for`, `begin` and highlight these structures differently.

Screenshot from 2020-04-09 17-00-41

Added new scopes:
`keyword.control.class.begin.ruby` for keyword `class`
`keyword.control.class.end.ruby` for keyword `end` which closes class
`meta.class.ruby` for everything between `class` and `end`

`keyword.control.module.begin.ruby` for keyword `module`
`keyword.control.module.end.ruby` for keyword `end` which closes module
`meta.module.ruby` for everything between `module` and `end`

`keyword.control.for.begin.ruby` for keyword `for`
`keyword.control.for.end.ruby` for keyword `end` which closes for loop
`meta.block.for.ruby` for everything between `for` and `end`

`keyword.control.do.begin.ruby` for keyword `do`
`keyword.control.do.end.ruby` for keyword `end` which closes do block
`meta.block.do.ruby` for everything between `do` and `end`

`keyword.control.begin.begin.ruby` for keyword `begin`
`keyword.control.begin.end.ruby` for keyword `end` which closes begin-end block
`meta.block.begin.ruby` for everything between `begin` and `end`

`keyword.control.conditional.case.begin.ruby` for keyword `case`
`keyword.control.conditional.case.end.ruby` for keyword `end` which closes case block
`meta.block.case.ruby` for everything between `case` and `end`

`keyword.control.conditional.if.begin.ruby` for keyword `if` (if block, not modifier)
`keyword.control.conditional.if.end.ruby` for keyword `end` which closes if block
`meta.block.if.ruby` for everything between `if` and `end`
`keyword.control.modifier.conditional.if.ruby` for `if` modifier (`perform if condition`)

`keyword.control.conditional.unless.begin.ruby` for keyword `unless` (unless block, not modifier)
`keyword.control.conditional.unless.end.ruby` for keyword `end` which closes unless block
`meta.block.unless.ruby` for everything between `unless` and `end`
`keyword.control.modifier.conditional.unless.ruby` for `unless` modifier (`perform unless condition`)

`keyword.control.while.begin.ruby` for keyword `while` (while block, not modifier)
`keyword.control.while.end.ruby` for keyword `end` which closes while block
`meta.block.while.ruby` for everything between `while` and `end`
`keyword.control.modifier.while.ruby` for `while` modifier (`perform while condition`)

`keyword.control.until.begin.ruby` for keyword `until` (until block, not modifier)
`keyword.control.until.end.ruby` for keyword `end` which closes until block
`meta.block.until.ruby` for everything between `until` and `end`
`keyword.control.modifier.until.ruby` for `until` modifier (`perform until condition`)

`keyword.control.def.begin.ruby` for keyword `def`
`keyword.control.def.end.ruby` for keyword `end` which closes method block
`meta.function.method.with-arguments.ruby` or `meta.function.method.without-arguments.ruby` for everything between `def` and `end`

`keyword.control.rescue.ruby` for keyword `rescue`
`keyword.control.ensure.ruby` for keyword `ensure`

`keyword.control.conditional.else.ruby` for keyword `else`
`keyword.control.conditional.elsif.ruby` for keyword `elsif`
`keyword.control.conditional.when.ruby` for keyword `when`
`keyword.control.conditional.then.ruby` for keyword `then`

`keyword.control.BEGIN.ruby` for keyword `BEGIN`
`keyword.control.END.ruby` for keyword `END`

`keyword.control.optional.do.ruby` for optional `do` like in for loop and while loop

`punctuation.accessor.singleton.ruby` for `<<` in expressions like `class << self`

Each `end` keyword also has a scope `keyword.control.end.ruby`

- [x] The build passes
- [x] TSLint is mostly happy
- [x] Prettier has been run

### CODE REVIEW

**Comment by graceful-potato** [comment]
For testing you can install this [theme](https://marketplace.visualstudio.com/items?itemName=GracefulPotato.gruvbox-ish)
It will override your current ruby grammar file after installation and you can switch to your favorite theme back.

**Review by wingrunr21 — APPROVED** [review]

**Comment by wingrunr21** [comment]
@graceful-potato can you update this to account for your two other PRs that I merged?

**Comment by graceful-potato** [comment]
@wingrunr21 ok, I will do it today.

**Comment by graceful-potato** [comment]
Wait, am I messed up with rebase somehow? I can see changes from  #641  but these changes already in the master. I am confused. @wingrunr21

**Comment by kylesnowschwartz** [comment]
This pull request is so exciting! Am I right in that it'll enable the development of going to matching `end` tags easily, such as in https://github.com/VSCodeVim/Vim/issues/1885 ?

**Comment by graceful-potato** [comment]
@kylesnowschwartz I am not sure about it. As far as i know its not so easy to get textmate scope from vscode extension. There is no API for that still.

**Comment by graceful-potato** [comment]
@kylesnowschwartz the only way I found so far is to parse it again within extension, then you can get all scopes and found everything you want. I tried to fix #656 with this approach and I think it works fine. The only disadvantage is the need to parse the file twice.

**Comment by graceful-potato** [comment]
Ping and quick update.
There will be 1 more way to define method in ruby3 called `Endless method definition`, so in order to correctly distinguish `end` keywords i need to treat this type of method definition separately.
I tried to quickly make a separate rule for this method, but turned out it is much more complicated than i thought.
It could be even impossible with this approach and looks like i need to rethink all rules related to methods.

**Comment by graceful-potato** [comment]
@wingrunr21 Hey there, I think i have a solution for endless methods.
Could you please reopen this PR if you are still intrested in this?

**Pull request closed without merging**
