### PR TITLE
Update indent pattern

### PR DESCRIPTION
**Pull request by TeeSeal**
- [ ] Build pass!
- [x] Follow VS Code [Coding Guidelines](https://github.com/Microsoft/vscode/wiki/Coding-Guidelines)

Refer the following pull request and the issues linked in it:
https://github.com/Microsoft/vscode/pull/40049

@rebornix 
This PR seems to come into a bit of conflict with #223, should make a decision on which one we're going to use.
 
Here's the thing:
1. If `case` doesn't indent the next line and `when` doesn't unindent, the indentation will be ok only while we're adding `when` clauses, but will break when we use `else` and/or `end` (because these 2  do unindent). The result of using the changes made in #233 would be this:
```rb
  case thing
  when 2 then true
  when 4 then false
else nil
end
```

2. With this PR the `case` statement does indent the next line but any of `when`, `else` and `end` will unindent leading to a desired output:

```rb
  case thing
  when 2 then true
  when 4 then false
  else nil
  end
```

### CODE REVIEW

**Comment by TeeSeal** [comment]
I also made the changes for `private` and `protected` defs the same way they are in the built in extension for Ruby of VS Code. This can now be considered in favor of #223 and #206.

I also edited the `[^\{;]` part to just `[^;]`. I didn't see the point of that curly brace there, and it made things such as:
```
  if string = /\d{4}/
  #not indent properly
end
```

**Comment by wingrunr21** [comment]
ping @rebornix

**Comment by wingrunr21** [comment]
Hi @TeeSeal 

Would you be willing to reopen this PR against my fork?

Fork: https://github.com/wingrunr21/vscode-ruby-lang

See https://github.com/rubyide/vscode-ruby/issues/239#issuecomment-359279950 for more information

Thanks!

**Comment by TeeSeal** [comment]
@wingrunr21 okay, will do!

**Comment by rebornix** [comment]
@TeeSeal your PR LGTM, thanks for your contribution.

**Comment by wingrunr21** [comment]
@rebornix 

@TeeSeal made additional updates to that intent and unindent patterns in the PR to my fork. It fixes a few other issues that are still in the patterns in this PR.

wingrunr21/vscode-ruby-lang#9

**Comment by TeeSeal** [comment]
Ye I thought this place is dead so I didn’t bother updating this source branch

**Comment by TeeSeal** [comment]
There are still some issues they are a bit harder to handle, Ill investigate those, see if I can do anything about them and open another PR

**Comment by rebornix** [comment]
@TeeSeal thanks, look forward to it ;)

**Pull request merged**
