### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by kachick**
When I'm digging a syntax highlight issue, found these typos. 😄 

- [x] The build passes
- [x] TSLint is mostly happy
- [x] Prettier has been run

### CODE REVIEW

**Comment by kachick** [comment]
The Ruby 2.4 CI failure might be fixed in https://github.com/rubyide/vscode-ruby/pull/710 🤔

**Comment by kachick** [comment]
https://github.com/rubyide/vscode-ruby/blob/7b5b6025caa2ebc140192e9add094aa34e7cec2d/packages/vscode-ruby/syntaxes/ruby.cson.json#L2-L6

I have already sent PR as https://github.com/atom/language-ruby/pull/294, but it is not been merged 😢

**Comment by wingrunr21** [comment]
I'm not using the upstream grammar anymore. There were too many unmerged fixes to it.

**Comment by kachick** [comment]
> I'm not using the upstream grammar anymore. There were too many unmerged fixes to it.

It sounds reasonable 👍 

Thanks for the merging!

**Pull request merged**
