### PR TITLE
Get modern rubyfmt working

### PR DESCRIPTION
**Pull request by wadetandy**
Per #627, the previous behavior of the rubyfmt formatter class included
an embedded version of the rubyfmt script. This isn't really a workable
solution anymore as the program has evolved beyond a simple ruby script
to include native modules.  This instead changes the formatter class to
rely on a `rubyfmt` executable on the user's `$PATH`.  Because rubyfmt
is not currently installable via bundler and is in a pre-release state,
users are expected to have followed the necessary installation
instructions from the [project
README](https://github.com/penelopezone/rubyfmt/blob/master/README.md#how-do-i-use-it).
The current instructions recommend adding an alias, but vscode will not
respect that (or at least vscode-ruby doesn't). Instead I have a
[commit](https://github.com/penelopezone/rubyfmt/pull/201/commits/19d5946a43b77de4be1083b3097b632dd79ab1bb)
submitted in [a PR](https://github.com/penelopezone/rubyfmt/pull/201)
which will make it easier to install an actual executable shim script.

- [x] The build passes
- [ ] TSLint is mostly happy
- [x] Prettier has been run

`yarn lint` is failing on a few things, but nothing in the changed files from this PR.

### CODE REVIEW

**Comment by wingrunr21** [comment]
Hey, thanks for this. Looks good overall. I do prefer using a shim on the Rubyfmt side but if Penelope prefers to direct people to use an alias we could keep the direct `ruby` call. It looks like the invocation is pretty close to the old version just with the addition of the Rust native extension.

The inability to use an alias is linked to node's `spawn`. A bash alias requires an interactive shell in order to be expanded and `spawn` does not support using an interactive shell.

**Comment by wingrunr21** [comment]
@wadetandy if this is ready I'm happy to merge it

**Comment by wadetandy** [comment]
I think this is ready to go with the caveat that it won't really work until the corresponding shim script PR in rubyfmt gets merged, which should hopefully be this week sometime.

**Comment by wadetandy** [comment]
Rubyfmt changes & vscode-ruby usage instructions were merged, so this should be GTG!

**Pull request merged**
