### PR TITLE
Readme improvements

### LINKED ISSUE #291: readme.md updates
I would like to take a stab at updating `readme.md`. Specifically:

- make the sections more explicit and add a Table of Contents
- link to the CHANGELOG
- add Contributing section

Any objections? Happy to take suggestions here before I start.

### PR DESCRIPTION
**Pull request by gurgeous**
Fixes #291. Feedback welcome.

### CODE REVIEW

**Comment by wingrunr21** [comment]
@rebornix this is the third PR that's randomly failed from AppVeyor (see #290 and #287). Is it adding value as a check here?

**Comment by wingrunr21** [comment]
@gurgeous Sorry for the delay here. I'd like to merge this but AppVeyor is failing and I don't have permissions to either rebuild AppVeyor or change the repo settings here to allow the merge

**Comment by gurgeous** [comment]
@rebornix, can we make @wingrunr21 an admin? I doubt you'll regret adding more admins :)

**Comment by rebornix** [comment]
There is no need to having CI validate markdown file changes. But the failing test of debugger looks suspicious though, I'll take a look.

**Comment by rebornix** [comment]
@gurgeous thank you for your help on this ;)

**Comment by gurgeous** [comment]
Happy to help! :)

**Pull request merged**
