### PR TITLE
Add `ruby.intellisense` configuration option

### PR DESCRIPTION
**Pull request by castwide**
- [x] Build pass!
- [X] Follow VS Code [Coding Guidelines](https://github.com/Microsoft/vscode/wiki/Coding-Guidelines)

This PR adds the `ruby.intellisense` configuration to allow method selection for go to/peek definition similar to `ruby.codeCompletion`. Valid options are `solargraph`, `rubyLocate`, and `none`.

### CODE REVIEW

**Comment by wingrunr21** [comment]
Should this PR also remove the [extension dependency on solargraph](https://github.com/rubyide/vscode-ruby/blob/master/package.json#L72-L74)?

**Comment by castwide** [comment]
The extension dependency is still necessary for the `solargraph` options to work. This PR helps ensure that only one intellisense provider is registered, so "go to definition" doesn't return duplicated entries.

**Comment by wingrunr21** [comment]
Gotcha. I guess my concern is if users select `rubyLocate` or `none`, they are going to wonder why the solargraph extension is a requirement if they are not using it.

**Comment by castwide** [comment]
Fair point. If neither `ruby.codeCompletion` nor `ruby.intellisense` is set to `solargraph`, the extension is not strictly required (although it will still provide access to documentation through the command palette). Making it a dependency is just the easiest way to integrate it.

**Comment by wingrunr21** [comment]
Ok. I'm going to open an issue on the topic (as I'm not convinced having it as a hard dependency is the right choice) but I also don't want to hold up this change. A standalone issue will allow other commentary and we can always remove the dependency later.

**Pull request merged**
