### PR TITLE
Enable conditional breakpoint support.

### PR DESCRIPTION
**Pull request by seraku24**
*(Now with no undesired commits...)*

This PR enables the commented-out code in the debug adapter that supports conditional breakpoints.

Tested against SketchUp/sketchup-ruby-debugger#11 which allows conditional breakpoints to be set.

---
- [x] Build pass!
- [x] Follow VS Code [Coding Guidelines](https://github.com/Microsoft/vscode/wiki/Coding-Guidelines)

### CODE REVIEW

**Comment by seraku24** [comment]
@rebornix, In doing some more testing, it seems that there is some oddness happening when breakpoint conditions are changed in VS Code.  The debug adapter sometimes receives two calls to `setBreakPointsRequest` in relatively quick succession with the first not showing the changes in the `args`.  The current logic for deleting all breakpoints and recreating them should technically work, however the first deletion does not complete fast enough, resulting in duplicate deletion commands over the `ruby-debug-ide` protocol.  Without conditional breakpoints, VS Code seems to behave normally without any extra calls resulting in unnecessary traffic across the protocol.

I have been looking into the possibility of tracking breakpoints more accurately so that it is not necessary to delete all breakpoints, but rather just send the minimal updates.  In theory, this means that the first call to `setBreakPointsRequest` where nothing has changed just becomes a bit no-op.

So at this point, I would recommend holding off on merging this PR until I can get a commit for this new work.

**Comment by rebornix** [comment]
@seraku24 thanks again for your contribution! When I started this project, I looked into conditional breakpoint but seems `ruby-debug-ide` doesn't work with conditional breakpoint command. But I may get things wrong at that time so I'd like to give your change a try :)

**Comment by seraku24** [comment]
@rebornix, no worries.  As I mentioned above, I have been helping out the `sketchup-ruby-debugger` project on a few issues and got conditional breakpoints working over there.

I can confirm that conditional breakpoints still appear to be unsupported in Ruby 2.0+ and `debase`.  Even running the latest version (0.2.2.beta9), conditional breakpoints are just treated as normal ones.  I filed an issue (denofevil/debase#36) on the `debase` project.

**Comment by seraku24** [comment]
@rebornix, I was able to get the breakpoint handling logic overhauled to workaround the issues I mentioned above.  Additionally, I encountered a few edge cases with unexpected input across the protocol while testing, so this commit includes fixes for them as well.

You will need a newer version of `debase` to be able to test the conditional breakpoints there.  I have a PR (denofevil/debase#37) over in that project, but the owner found a potential performance issue that we are trying to solve before it can be accepted.

Lastly, once this gets merged, I do believe that it fixes #95.

**Comment by Dashue** [comment]
Debug support is definitely dodgy at the moment, hope this will bring some stability to it!

**Comment by Dashue** [comment]
@seraku24 Looks like the debase issue has been merged as debase v0.2.2.beta10? Any way of getting some traction on this issue?

**Comment by seraku24** [comment]
@Dashue, not sure.  Haven't had time to look at Ruby in several months due to working on other projects.  Hopefully, @rebornix might be able to assist.

I do know that VSCode has made some changes to debugging in one of the recent releases, so I am not sure where this work sits with that.  I did just try updating the PR with changes from master but Travis CI is now failing due to many TypeScript issues, though AppVeyor seems to be working fine.  Unfortunately, I am not sure when I will have time to dig in more on Ruby stuff.

**Comment by Dashue** [comment]
Yeah currently I'm having to restart vscode to be able to add / remove breakpoints and have them actually being hit. Quite cumbersome.

**Comment by rebornix** [comment]
@seraku24 TypeScript 2 ships with typings file which conflict with ours. Now I just specify to use TypeScript 1.8 but I'll upgrade this project to 2 later on.

**Comment by rebornix** [comment]
@seraku24 thanks for your contribution to both this project and debase :)

**Pull request merged**
